### ISSUE TITLE
problems in the opl model

### ISSUE THREAD

**Issue by RayeZR** [MatthiasPercelay/Model-PPC#6]
**WorkdayAssignment:**
**Expressions:**
1. workDayDiff – will less work be a good thing? At present it is penalized 
2. breakprefpW – this should be maximized but is addded to the minimizing objective; and right now only reward when agent wants a break and is assigned a break (see objective) 
3. TotalweekEnd – should be maximized but added to the minimizing objective; no measure for each agent’s weekends
4. MAXVALs – some expressions can be simplified and some +1 of the upper boundary (not uniformed, no big deal as just used as weights)

**Objectives:**
1. Logic – workDayDiff penalize cases, also for break preferences
2. maximize – breakprefpW and TotalweekEnd should be maximized (subtract not add)
3. weights – at present using the maxvalue of variables, convention or should I change? And priorities among the objectives

**ShiftAssignment:
Expressions:**
1. some abundant expressions can be simplified (is_preference, fixedWork_)

**Comment by arnaud-m** [comment]
**WorkdayAssignment:
Expressions:**
1.  workDayDiff – The absolute difference between the expected and real number of work days. Yes it could be minimized
2. breakprefpW – this is subtracted, for instance in ObjectifCombi1234. The expression is really complicated. Could it be simplified ?
3. TotalweekEnd – Same thing, thus is substracted.
4. MAXVALs – Feel free to simplify the expression !

_You must select and simplify the objectives._

**Objectives:**

You can either use the MAX*** weight or use the staticLex aggregator.
The staticLex will simplify the objective definition but you should be careful that it does not degrade the performance.

**ShiftAssignment:
Expressions:**

Same thing ! You must select and simplify the objectives.
